version: "3.0"
services:
  node:
    build:
      context: .
      dockerfile: './build_files/Dockerfile'
    ports:
       - "8081:8080"
    volumes:
       - "/Applications/XAMPP/xamppfiles/htdocs/scaffold:/home/node/app"
    